name: Deploy prod

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - main 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Make build
        run: npm run build:prod

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v3
        with:
            folder: dist/pdp
            bucket: '${{ secrets.S3_DEV_BUCKET }}'
            bucket-region: '${{ secrets.S3_BUCKET_REGION }}'
            delete-removed: true